<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="5" total="6" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-03-02T20:58:08 EST" name="Default suite" finished-at="2021-03-02T20:59:17 EST" duration-ms="68622">
    <groups>
    </groups>
    <test started-at="2021-03-02T20:58:08 EST" name="Default test" finished-at="2021-03-02T20:59:17 EST" duration-ms="68622">
      <class name="tests.AssignmentTest">
        <test-method is-config="true" signature="createReports()[pri:0, instance:tests.AssignmentTest@747edf66]" started-at="2021-03-02T20:58:08 EST" name="createReports" finished-at="2021-03-02T20:58:08 EST" duration-ms="215" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createReports -->
        <test-method is-config="true" signature="launchBrowser()[pri:0, instance:tests.AssignmentTest@747edf66]" started-at="2021-03-02T20:58:08 EST" name="launchBrowser" finished-at="2021-03-02T20:58:13 EST" duration-ms="4352" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method signature="validateProblemUserTest()[pri:0, instance:tests.AssignmentTest@747edf66]" started-at="2021-03-02T20:58:13 EST" name="validateProblemUserTest" finished-at="2021-03-02T20:59:16 EST" duration-ms="63306" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at tests.BaseTest.assertTrue(BaseTest.java:73)
at tests.AssignmentTest.validateProblemUserTest(AssignmentTest.java:106)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateProblemUserTest -->
        <test-method is-config="true" signature="quitBrowser()[pri:0, instance:tests.AssignmentTest@747edf66]" started-at="2021-03-02T20:59:16 EST" name="quitBrowser" finished-at="2021-03-02T20:59:17 EST" duration-ms="857" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quitBrowser -->
        <test-method is-config="true" signature="flushReports()[pri:0, instance:tests.AssignmentTest@747edf66]" started-at="2021-03-02T20:59:17 EST" name="flushReports" finished-at="2021-03-02T20:59:17 EST" duration-ms="363" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- flushReports -->
      </class> <!-- tests.AssignmentTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
